# fly.toml file generated for watchmate on 2022-09-14T14:37:25-05:00

app = "watchmate"
kill_signal = "SIGINT"
kill_timeout = 5


[build]
  builder = "heroku/buildpacks:latest"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
